name: build and deploy functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: Transpile TypeScript (npx tsc)
        run: npx tsc --project source
      - name: deploy functions to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: tsukumart-f0971
